### ISSUE TITLE
Create a plan of Bc thesis

### ISSUE THREAD

**Issue by iradche** [IPMITMO/github-archive-miner#1]
Create a file in Google Docs.

**Comment by beltasha** [comment]
[План работы](https://docs.google.com/document/d/1a6ga16N1_6XTAR23qJzgZ1xF1xitUWPQeyZF33PDKC8/edit?usp=sharing)

**Comment by iradche** [comment]
Pull-request https://github.com/IPMITMO/github-archive-miner/pull/13

**Comment by iradche** [comment]
Pull-request https://github.com/IPMITMO/github-archive-miner/pull/13
