### ISSUE TITLE
Create a plan for ITGM #9 

### ISSUE THREAD

**Issue by iradche** [IPMITMO/github-archive-miner#19]
- ITGM#9: http://piter-united.ru/itgm9/itgm.html
- https://docs.google.com/spreadsheets/d/1EXtirtbXD9aD4Ycc7SV4aE25dO6_zxmYz_BECjFDKJQ/edit

- [ ] Добавить ссылку на фотографию: https://docs.google.com/spreadsheets/d/1EXtirtbXD9aD4Ycc7SV4aE25dO6_zxmYz_BECjFDKJQ/edit#gid=1217258751

- [ ]  Добавить должность: https://docs.google.com/spreadsheets/d/1EXtirtbXD9aD4Ycc7SV4aE25dO6_zxmYz_BECjFDKJQ/edit#gid=1217258751

**Comment by annkupriyanova** [comment]
done
