### ISSUE TITLE
Discover GitHub Archive 

### ISSUE THREAD

**Issue by iradche** [IPMITMO/github-archive-miner#2]

**Comment by iradche** [comment]
https://www.githubarchive.org/

**Comment by beltasha** [comment]
Write a list of topics, I could mine

**Comment by iradche** [comment]
How to list all GitHub users? http://stackoverflow.com/questions/7329978/how-to-list-all-github-users

**Comment by annkupriyanova** [comment]
https://habrahabr.ru/post/312596/
