### ISSUE TITLE
Try Google BigQuery to get GitHub data

### ISSUE THREAD

**Issue by annkupriyanova** [IPMITMO/github-archive-miner#24]
Get data from the start of GitHub to 2010

**Comment by annkupriyanova** [comment]
@iradche @beltasha 
Found an interesting web-service about GitHub. It calculates your GitHub distance from most famous people there. I tried to calculate it from Linus Torvalds. And it is still calculating (perhaps because I almost don't have connections)
http://graphub.yodas.com

**Comment by iradche** [comment]
You could use their list.
![2016-11-19 19 07 13](https://cloud.githubusercontent.com/assets/2790096/20456632/7ceedd80-ae8b-11e6-9d09-f5e9891d0084.png)

**Comment by annkupriyanova** [comment]
Yes, I saw this

**Comment by annkupriyanova** [comment]
GitHub Archive scheme:
https://github.com/igrigorik/githubarchive.org/blob/master/bigquery/schema.js

**Comment by annkupriyanova** [comment]
@iradche @beltasha 
As far as I understood GitHub Archive organises data around GitHub activities (events). And to get users we have to read data of the events of certain type. But this is not convenient and sensible. 
**_Maybe my guess is wrong?_**

**Comment by beltasha** [comment]
https://bigquery.cloud.google.com/dataset/ghtorrent-bq:ght
let's use this! :)

**Comment by annkupriyanova** [comment]
Everything is all right. **We managed to get data from GHTorrent dataset through Google BigQuery.**

**Comment by iradche** [comment]
Show your results and good luck
