### ISSUE TITLE
Discover a public dataset on Google BigQuery

### ISSUE THREAD

**Issue by iradche** [IPMITMO/github-archive-miner#3]

**Comment by iradche** [comment]
https://cloud.google.com/bigquery/docs/

**Comment by beltasha** [comment]
Add first query - Get most active github users  - https://gist.github.com/paulmillr/2657075

**Comment by iradche** [comment]
https://habrahabr.ru/post/304476/

**Comment by annkupriyanova** [comment]
https://habrahabr.ru/post/312596/

**Comment by beltasha** [comment]
google bigquery has some technical restrictions - not found any way to get the whole users' information;
decided to use github api
