### ISSUE TITLE
Get familiar with Cloud9

### ISSUE THREAD

**Issue by iradche** [IPMITMO/github-archive-miner#5]

**Comment by iradche** [comment]
https://github.com/tcnksm/awesome-container
https://github.com/veggiemonk/awesome-docker

**Comment by beltasha** [comment]
deploy first application on docker

**Comment by iradche** [comment]
https://startpack.ru/application/cloud9/alternatives

**Comment by beltasha** [comment]
created an account - https://ide.c9.io/beltasha/
